### ISSUE TITLE
Move wasserportal functions to their own package

### ISSUE THREAD

**Issue by hsonne** [KWB-R/kwb.read#10]
kwb.read is not the right place. It contains too many KWB (and BWB) specific functions some of which are a mess.

**Comment by mrustl** [comment]
Ok. Package name `kwb.wasserportal` ? Should I prepare the pkg skeleton?

**Comment by hsonne** [comment]
Maybe just "wasserportal"? So that we get some clicks by google. 
Please wait until I get things fixed.

**Comment by mrustl** [comment]
Ok...did some commits on branch [wasserportal](https://github.com/KWB-R/kwb.read/tree/wasserportal)
