### ISSUE TITLE
wasserportal: add stations for GW level (quality)

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.read#4]
@HScKWB asked @jmielk today for DWC to search for GW data in the [Wasserportal Berlin](https://wasserportal.berlin.de)
https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gws
https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gwq

**GW stations overview**
level: https://wasserportal.berlin.de/messwerte.php?anzeige=tabelle&thema=gws&nstoffid=10
quality: https://wasserportal.berlin.de/messwerte.php?anzeige=tabelle&thema=gwq

May be this data / stations can be added to kwb.read and the `stations` can be updated here: 
https://github.com/KWB-R/kwb.read/blob/dev/inst/extdata/stations_wasserportal.csv

**Comment by hsonne** [comment]
>https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gwl

Do you mean `thema=gws`?
https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gws

**Comment by HScKWB** [comment]
Ja, scheint so.

:o)



Dr. Hella Schwarzmüller
Head of Groundwater Department / Bereichsleiterin Grundwasser
Phone +49 (0)30 536 53814
Mobile +49 (0)151 688 088 56

[kwb_signatur_logo]<https://www.kompetenz-wasser.de/de/>

Follow us on:

 [cid:image003.png@01D6C283.AFDAE170] <https://twitter.com/kompetenzwasser>   [cid:image004.png@01D6C283.AFDAE170] <https://de.linkedin.com/company/kompetenzzentrum-wasser-berlin>

Von: Hauke Sonnenberg <notifications@github.com>
Gesendet: Montag, 1. März 2021 16:12
An: KWB-R/kwb.read <kwb.read@noreply.github.com>
Cc: Hella Schwarzmüller <Hella.Schwarzmueller@kompetenz-wasser.de>; Mention <mention@noreply.github.com>
Betreff: Re: [KWB-R/kwb.read] wasserportal: add stations for GW level (quality) (#4)


https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gwl

Do you mean thema=gws?
https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gws

**Comment by mrustl** [comment]
> 
> 
> > https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gwl
> 
> Do you mean `thema=gws`?
> https://wasserportal.berlin.de/messwerte.php?anzeige=karte&thema=gws

Yes updated accordingly. @hsonne do you know if the Senate already published an API for the Wasserportal (see slide from Open Data Day 2019 below): 

![grafik](https://user-images.githubusercontent.com/11964451/109616291-4a011480-7b35-11eb-98a0-1a64b5fd86a6.png)
Source: https://projektzukunft.berlin.de/fileadmin/user_upload/pdf/pr%C3%A4sentationen/Pr%C3%A4sentationen_Boddy2019/WasserPortalBerlin_Schroeder_OpenDataLINK.pdf#page=12

**Comment by hsonne** [comment]
@mrustl No, no idea.

**Comment by mrustl** [comment]
Now to be done in R package `wasserportal` (-> https://github.com/KWB-R/wasserportal/issues/3)
